### ISSUE TITLE
failing tests (specifcally getSymbolData)

### ISSUE THREAD

**Issue by maximus12793** [sjev/trading-with-python#6]
CParserError: Error tokenizing data. C error: Expected 1 fields in line 4, saw 2
The request method seems to be broken and the token is no longer authenticated. any idea?

^this is actually mainly an issue of get_token working I would guess. The authentication is returning 401 response so perhaps yahoo has modified their token generation.

**Comment by sjev** [comment]
Yes, the test fails sporadically, caused by YF returning a 401 response.  Most of the time it works though. 
I've added a check for correct response, so the error is more descriptive. Otherwise than that, I'm afraid there is nothing to do about it.
