### ISSUE TITLE
issue or newbee mistake

### ISSUE THREAD

**Issue by rolero** [sjev/trading-with-python#7]
I was trying out the following:

![image](https://user-images.githubusercontent.com/2805313/28071897-e81ad860-6683-11e7-812f-e85b45c7289d.png)

I was testing if I would be able to get the date column of last downloaded record to use it further in the process but it keeps giving me the following result:

![image](https://user-images.githubusercontent.com/2805313/28071992-29ef511c-6684-11e7-9b89-5a5078168b9b.png)

Why it gives me the value from the first two columns?

What am I doing wrong?

**Comment by rolero** [comment]
Seems I am a real newbie. Was able to solve it like this: 
![image](https://user-images.githubusercontent.com/2805313/28119864-e5fe0ece-6748-11e7-85e0-24f1b542bbe1.png)

**Comment by sjev** [comment]
So, no problem then! :-)
