### ISSUE TITLE
HTTP 403 on getQuote()

### ISSUE THREAD

**Issue by Jedtek** [sjev/trading-with-python#8]
The getQuote() function returns a HTTP 403 and it gives out this message:
It has come to our attention that this service is being used in violation of the Yahoo Terms of Service. As such, the service is being discontinued. For all future markets and equities data research, please refer to finance.yahoo.com.

Just to clarify on if it might be my setup, getSymbolData() is working fine.

Thanks,
Jed.

**Comment by sjev** [comment]
So long, and thanks for all the quotes ...
