### ISSUE TITLE
Issue when pulling multiple symbols from Yahoo Finance (ValueError: Shape of passed values)

### ISSUE THREAD

**Issue by sslack88** [sjev/trading-with-python#9]
When trying to pull a list of S&P 500 Symbols from Yahoo Finance using getHistoricData the error "ValueError: Shape of passed values is (3030, 178), indices imply (3030, 176)" is consistently returned.

Have you thought about using "join" instead of "concat" in the code?  It seems that's [how others have resolved this type of error](https://stackoverflow.com/questions/27719407/pandas-concat-valueerror-shape-of-passed-values-is-blah-indices-imply-blah2). 

Here is the symbol list if you want to replicate the error:
[sp500-symbols-30jun2018.csv.zip](https://github.com/sjev/trading-with-python/files/2379399/sp500-symbols-30jun2018.csv.zip)

**Comment by sjev** [comment]
yfinance is the way to download data nowdays
